// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID
	Title     string
	Slug      string
	S3Key     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
